# app.py
from src.graph import app
from src.pdf_generator import create_pdf
import sys
import os
import tkinter as tk
from tkinter import filedialog

def get_save_path(ticker):
    """
    Opens a system file dialog to choose the save location for the report.
    This provides a professional user experience.
    """
    root = tk.Tk()
    root.withdraw()  # Hide the main tkinter window
    root.attributes("-topmost", True) # Bring the dialog to the front
    
    default_filename = f"{ticker}_Investment_Report.pdf"
    file_path = filedialog.asksaveasfilename(
        initialfile=default_filename,
        defaultextension=".pdf",
        filetypes=[("PDF files", "*.pdf"), ("All files", "*.*")],
        title=f"Save Investment Report for {ticker}"
    )
    root.destroy()
    return file_path

def main():
    print("🚀 AI Investment Committee initialized...")
    
    # 1. User Input and Cleanup
    ticker_input = input("Enter a stock ticker (e.g., AAPL, TSLA, PAGS): ").upper()
    # Basic cleanup to handle common entry errors (like 'XP Inc' or 'XP.')
    ticker = ticker_input.replace(" INC", "").replace(".", "").strip()
    
    if not ticker:
        print("❌ Error: Ticker is required.")
        return

    # 2. Execute the Multi-Agent Graph
    print(f"\n--- STARTING ANALYSIS FOR {ticker} ---\n")
    initial_state = {"ticker": ticker, "messages": []}
    
    try:
        # This triggers the Researcher, Analyst, and Writer in sequence/parallel
        result = app.invoke(initial_state)
        report_content = result.get("final_report", "")
        chart_path = result.get("chart_path", "") # Path to the .png generated by the Analyst
        
        if not report_content:
            print("❌ Error: The agents failed to generate a report.")
            return

        # 3. Display Markdown Report in Console (for immediate feedback)
        print("\n" + "="*50)
        print("       FINAL INVESTMENT REPORT")
        print("="*50 + "\n")
        print(report_content)
        
        # 4. Save to PDF (The Final Product)
        print("\n" + "="*50)
        print(f"📄 SELECT SAVE LOCATION FOR {ticker}...")
        
        save_path = get_save_path(ticker)
        
        if not save_path:
            print("⚠️ Save cancelled by user. PDF not generated.")
            # Clean up the temporary chart if the user cancels
            if chart_path and os.path.exists(chart_path):
                os.remove(chart_path)
            return

        # Create the professional PDF with the embedded chart
        create_pdf(ticker, report_content, save_path, chart_path)
        
        print(f"✅ SUCCESS! Report saved at:\n👉 {save_path}")
        print("="*50)
        
        # 5. Cleanup & Post-processing
        # Delete the temporary chart image file so it doesn't clutter the root folder
        if chart_path and os.path.exists(chart_path):
            os.remove(chart_path)
            
        # Automatically open the PDF for the user
        if sys.platform == 'win32':
            os.startfile(save_path)
        elif sys.platform == 'darwin': # Mac
            os.system(f'open "{save_path}"')
            
    except Exception as e:
        print(f"❌ Critical Error during execution: {str(e)}")

if __name__ == "__main__":
    main()